Mod creative tab and stuff
Tiph-Studios/DysonSphereProject pull request #59
Opened 2023-12-14 22:07 UTC by PJWahlgren

Also updated language for stuff

2023-12-15 16:25 UTC, cmpashak requested changes

2023-12-15 16:25 UTC, cmpashak commented on src/main/resources/assets/dysonsphereproject/lang/en_us.json
> +  "creativetab.dsp_tab": "Dyson Sphere Project"
keep the naming convention - creativetab.dysonsphereproject.tab

2023-12-15 20:20 UTC, zhouzhouthezhou requested changes

2023-12-15 20:20 UTC, zhouzhouthezhou commented on src/main/java/com/tiph/dysonsphereproject/common/items/ModCreativeModeTabs.java
> +package com.tiph.dysonsphereproject.common.items;
Does not belong in items, maybe move to init or common?

2023-12-15 20:23 UTC, zhouzhouthezhou commented on src/main/java/com/tiph/dysonsphereproject/common/items/ModCreativeModeTabs.java
> +        "dsp_tab",
same as connors review
dysonsphereproject.tab

2023-12-15 20:24 UTC, zhouzhouthezhou commented on src/main/java/com/tiph/dysonsphereproject/common/items/ModCreativeModeTabs.java
> +                .title(Component.translatable("creativetab.dsp_tab"))
here too

2023-12-15 20:26 UTC, zhouzhouthezhou requested changes

2023-12-15 20:26 UTC, zhouzhouthezhou commented on src/main/java/com/tiph/dysonsphereproject/common/items/ModCreativeModeTabs.java
> +                      output.accept(DysonBlocks.getBasicBlock(BasicBlocks.EXAMPLE_BASIC_BLOCK));
make basic blocks loop through map so we don't need to update everytime we add one

2023-12-15 20:26 UTC, zhouzhouthezhou commented on src/main/java/com/tiph/dysonsphereproject/common/items/ModCreativeModeTabs.java
> +                      output.accept(DysonItems.getBasicItem(BasicItems.MIRROR));
make basic items do the same

2023-12-15 20:29 UTC, zhouzhouthezhou commented on src/main/java/com/tiph/dysonsphereproject/common/items/ModCreativeModeTabs.java
> +                      output.accept(DysonBlocks.SOLAR_GENERATOR);
out of scope for this pr but we probably are are going to want to somehow automate this as well across all inits

2023-12-15 20:30 UTC, zhouzhouthezhou requested changes

2023-12-15 20:30 UTC, zhouzhouthezhou commented on src/main/java/com/tiph/dysonsphereproject/common/items/ModCreativeModeTabs.java
Also please rename to DysonCreativeModeTabs

2023-12-16 20:13 UTC, cmpashak requested changes

2023-12-16 20:13 UTC, cmpashak commented on src/main/java/com/tiph/dysonsphereproject/common/init/ModCreativeModeTabs.java
> +public class ModCreativeModeTabs {
rename this to DysonCreativeModeTab

2023-12-16 20:35 UTC, cmpashak approved these changes

2023-12-16 20:43 UTC, merged